apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: voting-app
data:
  REDIS_HOST: redis-master #for the local files use  redis and redis-master for helm
  REDIS_PORT: "6379"
  POSTGRES_HOST: db
  POSTGRES_DB: postgres
  POSTGRES_PORT: "5432"