services:
  vote:
    container_name: vote_container
    build: ./vote
    ports:
      - 8080:8080
    volumes:
      - ./vote:/app

    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - internal_network
      - external_network

  redis:
    image: redis:alpine
    container_name: redis-db
    networks:
      - internal_network
    volumes:
      - redis_data:/data

      - ./healthchecks/redis.sh:/healthchecks/redis.sh
    healthcheck:
      test: [CMD, sh, /healthchecks/redis.sh]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 40s

  result:
    container_name: result_container
    build: ./result
    ports:
      - 8081:8081
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/postgres
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - internal_network
      - external_network

  db:
    image: postgres:14-alpine
    container_name: postgres
    networks:
      - internal_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./healthchecks/postgres.sh:/healthchecks/postgres.sh
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [CMD, sh, /healthchecks/postgres.sh]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 40s

  worker:
    container_name: worker_container
    build: ./worker
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
    internal: true # No external internet access
  external_network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
