apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-netpol
  namespace: voting-app
spec:
  podSelector:
    matchLabels:
     # app: redis #for the local files
      kubernetes.io/instance: redis
  policyTypes:
  - Ingress
  ingress:
  # Allow only vote and worker to access redis
  - from:
    - podSelector:
        matchLabels:
          app: vote
    - podSelector:
        matchLabels:
          app: worker
  - from:
        - podSelector:
            matchLabels:
              app: vote
    
    ports:
    - protocol: TCP
      port: 6379